CREATE TABLE `t_bank_bill` (
`bill_id`  varchar(200) NOT NULL COMMENT '账单id' ,
`bank_id`  int(20) NULL DEFAULT 0 COMMENT '银行id' ,
`bank_name`  varchar(100) NOT NULL COMMENT '银行名称' ,
`card_type`  smallint(2) NULL COMMENT '卡种类,信用卡或借记卡' ,
`bill_month`  datetime NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '账单月份,信用卡-账单月；借记卡-自然月' ,
`bill_date`  datetime NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '账单日' ,
`payment_due_date`  datetime NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '还款日' ,
`new_balance`  decimal(8,6) NULL COMMENT '本期账单金额' ,
`usd_new_balance`  decimal(8,6) NULL COMMENT '本期账单金额-美元' ,
`min_payment`  decimal(8,6) NULL COMMENT '最低还款额' ,
`usd_min_payment`  decimal(8,6) NULL COMMENT '最低还款额-美元' ,
`last_balance`  decimal(8,6) NULL COMMENT '上期账单金额' ,
`usd_last_balance`  decimal(8,6) NULL COMMENT '上期账单金额-美元' ,
`last_payment`  decimal(8,6) NULL COMMENT '上期还款金额' ,
`usd_last_payment`  decimal(8,6) NULL COMMENT '上期还款金额-美元' ,
`usd_new_charges`  decimal(8,6) NULL COMMENT '本期新增款额-美元' ,
`interest`  decimal(8,6) NULL COMMENT '循环利息' ,
`usd_interest`  decimal(8,6) NULL COMMENT '循环利息-美元' ,
`credit_limit`  decimal(8,6) NULL COMMENT '信用卡额度' ,
`usd_credit_limit`  decimal(8,6) NULL COMMENT '信用卡额度-美元' ,
`cash_limit`  decimal(8,6) NULL COMMENT '预借现金金额' ,
`usd_cash_limit`  decimal(8,6) NULL COMMENT '预借现金金额-美元' ,
`card_nums`  varchar(10) NULL COMMENT '卡号末四位' ,
`full_card_nums`  varchar(100) NULL COMMENT '完整卡号' ,
`name_on_card`  varchar(50) NULL COMMENT '持卡人' ,
`bill_item_count`  int(100) NULL COMMENT '账单明细条数' ,
`user_id`  varchar(200) NULL COMMENT '用户id'
)
;
